// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	baz "github.com/Marcos30004347/k8s-custom-API-Server/pkg/apis/baz"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Foo)(nil), (*baz.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Foo_To_baz_Foo(a.(*Foo), b.(*baz.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.Foo)(nil), (*Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_Foo_To_v1beta1_Foo(a.(*baz.Foo), b.(*Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooBar)(nil), (*baz.FooBar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooBar_To_baz_FooBar(a.(*FooBar), b.(*baz.FooBar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.FooBar)(nil), (*FooBar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_FooBar_To_v1beta1_FooBar(a.(*baz.FooBar), b.(*FooBar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooList)(nil), (*baz.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooList_To_baz_FooList(a.(*FooList), b.(*baz.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.FooList)(nil), (*FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_FooList_To_v1beta1_FooList(a.(*baz.FooList), b.(*FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooSpec)(nil), (*baz.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooSpec_To_baz_FooSpec(a.(*FooSpec), b.(*baz.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.FooSpec)(nil), (*FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_FooSpec_To_v1beta1_FooSpec(a.(*baz.FooSpec), b.(*FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooStatus)(nil), (*baz.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FooStatus_To_baz_FooStatus(a.(*FooStatus), b.(*baz.FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*baz.FooStatus)(nil), (*FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_baz_FooStatus_To_v1beta1_FooStatus(a.(*baz.FooStatus), b.(*FooStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Foo_To_baz_Foo(in *Foo, out *baz.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_FooSpec_To_baz_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_FooStatus_To_baz_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Foo_To_baz_Foo is an autogenerated conversion function.
func Convert_v1beta1_Foo_To_baz_Foo(in *Foo, out *baz.Foo, s conversion.Scope) error {
	return autoConvert_v1beta1_Foo_To_baz_Foo(in, out, s)
}

func autoConvert_baz_Foo_To_v1beta1_Foo(in *baz.Foo, out *Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_baz_FooSpec_To_v1beta1_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_baz_FooStatus_To_v1beta1_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_baz_Foo_To_v1beta1_Foo is an autogenerated conversion function.
func Convert_baz_Foo_To_v1beta1_Foo(in *baz.Foo, out *Foo, s conversion.Scope) error {
	return autoConvert_baz_Foo_To_v1beta1_Foo(in, out, s)
}

func autoConvert_v1beta1_FooBar_To_baz_FooBar(in *FooBar, out *baz.FooBar, s conversion.Scope) error {
	out.Name = in.Name
	out.Quantity = in.Quantity
	return nil
}

// Convert_v1beta1_FooBar_To_baz_FooBar is an autogenerated conversion function.
func Convert_v1beta1_FooBar_To_baz_FooBar(in *FooBar, out *baz.FooBar, s conversion.Scope) error {
	return autoConvert_v1beta1_FooBar_To_baz_FooBar(in, out, s)
}

func autoConvert_baz_FooBar_To_v1beta1_FooBar(in *baz.FooBar, out *FooBar, s conversion.Scope) error {
	out.Name = in.Name
	out.Quantity = in.Quantity
	return nil
}

// Convert_baz_FooBar_To_v1beta1_FooBar is an autogenerated conversion function.
func Convert_baz_FooBar_To_v1beta1_FooBar(in *baz.FooBar, out *FooBar, s conversion.Scope) error {
	return autoConvert_baz_FooBar_To_v1beta1_FooBar(in, out, s)
}

func autoConvert_v1beta1_FooList_To_baz_FooList(in *FooList, out *baz.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]baz.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_FooList_To_baz_FooList is an autogenerated conversion function.
func Convert_v1beta1_FooList_To_baz_FooList(in *FooList, out *baz.FooList, s conversion.Scope) error {
	return autoConvert_v1beta1_FooList_To_baz_FooList(in, out, s)
}

func autoConvert_baz_FooList_To_v1beta1_FooList(in *baz.FooList, out *FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_baz_FooList_To_v1beta1_FooList is an autogenerated conversion function.
func Convert_baz_FooList_To_v1beta1_FooList(in *baz.FooList, out *FooList, s conversion.Scope) error {
	return autoConvert_baz_FooList_To_v1beta1_FooList(in, out, s)
}

func autoConvert_v1beta1_FooSpec_To_baz_FooSpec(in *FooSpec, out *baz.FooSpec, s conversion.Scope) error {
	out.Bar = *(*[]baz.FooBar)(unsafe.Pointer(&in.Bar))
	return nil
}

// Convert_v1beta1_FooSpec_To_baz_FooSpec is an autogenerated conversion function.
func Convert_v1beta1_FooSpec_To_baz_FooSpec(in *FooSpec, out *baz.FooSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_FooSpec_To_baz_FooSpec(in, out, s)
}

func autoConvert_baz_FooSpec_To_v1beta1_FooSpec(in *baz.FooSpec, out *FooSpec, s conversion.Scope) error {
	// INFO: in.Bar opted out of conversion generation
	return nil
}

// Convert_baz_FooSpec_To_v1beta1_FooSpec is an autogenerated conversion function.
func Convert_baz_FooSpec_To_v1beta1_FooSpec(in *baz.FooSpec, out *FooSpec, s conversion.Scope) error {
	return autoConvert_baz_FooSpec_To_v1beta1_FooSpec(in, out, s)
}

func autoConvert_v1beta1_FooStatus_To_baz_FooStatus(in *FooStatus, out *baz.FooStatus, s conversion.Scope) error {
	out.Cost = in.Cost
	return nil
}

// Convert_v1beta1_FooStatus_To_baz_FooStatus is an autogenerated conversion function.
func Convert_v1beta1_FooStatus_To_baz_FooStatus(in *FooStatus, out *baz.FooStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_FooStatus_To_baz_FooStatus(in, out, s)
}

func autoConvert_baz_FooStatus_To_v1beta1_FooStatus(in *baz.FooStatus, out *FooStatus, s conversion.Scope) error {
	out.Cost = in.Cost
	return nil
}

// Convert_baz_FooStatus_To_v1beta1_FooStatus is an autogenerated conversion function.
func Convert_baz_FooStatus_To_v1beta1_FooStatus(in *baz.FooStatus, out *FooStatus, s conversion.Scope) error {
	return autoConvert_baz_FooStatus_To_v1beta1_FooStatus(in, out, s)
}
